No access control on OPTIONS method
cundd/rest pull request #39
Opened 2017-09-07 10:11 UTC by stuartmcfarlane

The OPTIONS method is neither a read nor write
operation. When used for preflight CORS header
discovery no auth can be sent.

This solution changed the isWrite method to
assert that an OPTIONS request is not a write
request. Further the ConfigurationBasedAccessController
is changed to allow requests are neither read
nor write.

2017-09-07 10:31 UTC, cundd commented
Thank you for the investigation and your work!

Does it finally solve your problem? Doesn't it result in a 404 response, or did you create a custom handler which implements a route for `OPTIONS`?

2017-09-07 10:52 UTC, stuartmcfarlane commented
I did add a n OPTIONS method handler on the route.

A more general solution might useful. Like all registered routes get an automatic OPTION method handler that is informed by the plugin.tx_rest.settings.responseHeaders typoscript settings. But the first step is disbling auth checks on the OPTIONS method

2017-09-07 11:04 UTC, cundd commented
Thank you for the clarification. I think I would prefer a separate method in addition to `isRead` and `isWrite`. Maybe called `isPreflight` or just `isOption`.

2017-09-07 11:20 UTC, stuartmcfarlane commented
perhaps requiresAuth() ?

2017-09-07 11:23 UTC, cundd commented
I would add the method to the Rest Request - which doesn't know if auth is required later in the pipeline

2017-09-07 11:31 UTC, cundd commented
I'm thinking if it would make sense to create a new `AccessControllerInterface::ACCESS` constant for such requests

2017-09-08 07:41 UTC, stuartmcfarlane commented
Adding it to the `Request` feels a bit odd. The `Request` knows nothing of authorization

2017-09-08 08:13 UTC, cundd commented
Oh. That's what I wanted to say. 

I'll add a `isOptions` or `isPreflight` to the request, afterwards. 

In the afternoon I'll try to fix the CI tests and then have a final look at your PR.

2017-09-08 08:26 UTC, stuartmcfarlane commented
I couldn't resist a little bit of refactoring. I've put it in separate commits. I'm happy enough to revert them if you don't like then.

2017-09-08 14:00 UTC, cundd requested changes
I like the simplification of the code! But there is a small problem (if I didn't made a mistake). 

The line [ ConfigurationBasedAccessController.php#L161](https://github.com/stuartmcfarlane/rest/blob/54bc55e213e5741f6bc7911070a3e3681e11c5fb/Classes/Access/ConfigurationBasedAccessController.php#L161) will never evaluate to `true` since `getAccess()` will never return `AccessControllerInterface::ACCESS_REQUIRE_LOGIN` because `checkAuthentication()` will be called before. Do you think so too?

I think this is the result of an architecture failure of me.

2017-09-08 14:10 UTC, stuartmcfarlane commented
I found the code confusing and I believe immediately that I got it wrong 😄 . I'll have another look

2017-09-08 14:15 UTC, cundd commented
I'd create an additional method like the following and call that from the other two

```php
 private function getAccessConfiguration(RestRequestInterface $request)
    {
        if (!$this->requiresAuthorization($request)) {
            return AccessControllerInterface::ACCESS_ALLOW;
        }

        $configurationKey = self::ACCESS_METHOD_READ;
        if ($request->isWrite()) {
            $configurationKey = self::ACCESS_METHOD_WRITE;
        }

        $configuration = $this->getConfigurationForResourceType(new ResourceType($request->getResourceType()));
        // Throw an exception if the configuration is not complete
        if (!isset($configuration[$configurationKey])) {
            throw new InvalidConfigurationException($configurationKey . ' configuration not set', 1376826223);
        }

        return $configuration[$configurationKey];
    }
```

2017-09-08 16:12 UTC, cundd commented
I want to merge the changes. I'll merge and revert ddfb5be for now, so that we can work on it later :)

2017-09-08 16:13 UTC, merged